name: Lint Code and Create PR

on:
  workflow_dispatch:

jobs:
  lint-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: 🤘 Checkout
        uses: actions/checkout@v4

      - name: 📦 Install dependencies
        run: dotnet tool restore

      - name: 🧹 Format C# files
        run: dotnet csharpier .

      - name: Create Pull Request with applied fixes
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: csharp-lint
          author: csharpier[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "[CSharpier] Apply linters automatic fixes"
          title: "[CSharpier] Apply linters automatic fixes"
          labels: bot
